# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912cf600abfd355b0672ae88670184d0cc79325773d56d6792e92ed5c08acc43426d9b767a710086f0102a85d6604f9ee536f8482ee2490a72712c566a0bdd71

test:
  secret_key_base: ec36c818b7f20542e38341a281a84307322bf7bf03a30a91a091bb4d6b74f359de2f09021f29ad6de42511f543575c475a86d85f8cb5cd84c2c7d64d0d3ef380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
